spring:
 application:
  name: spring-boot-security-oauth-google
#  
server:
 port: 8082

security:
   oauth2:
     client:
        clientId: id_here
        clientSecret: secret_here
        accessTokenUri: https://github.com/login/oauth/access_token
        userAuthorizationUri: https://github.com/login/oauth/authorize
        tokenName: oauth_token
        authenticationScheme: query
        clientAuthenticationScheme: form
        scope : 
         - profile
         - email
      
     resource:
        userInfoUri: https://api.github.com/user
        
        
        


      
