spring:
 application:
  name: spring-boot-security-oauth
# security:
#  oauth2:
#   client:
#    registration:
#     facebook:
#      clientId : 1438529286840893
#      clientSecret : c4a65bcd94ce659c705856d7e52f2193
#      redirectUriTemplate : http://localhost:8082/api/v1/8082
#  
server:
 port: 8082

security:
   oauth2:
     client:
        clientId: 1438529286840893
        clientSecret: c4a65bcd94ce659c705856d7e52f2193
        accessTokenUri: https://graph.facebook.com/oauth/access_token
        userAuthorizationUri: https://www.facebook.com/dialog/oauth
        tokenName: oauth_token
        authenticationScheme: query
        clientAuthenticationScheme: form
       
     resource:
        userInfoUri: https://graph.facebook.com/me
        
        


      
